---
title: "TA session5"
subtitle: 
author: "Xiaoqin Wang"
date: " `r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```
# 主要内容
## 复习  Classification 和 Model Selection
## 演示两个例子： Ketchup 和 Employment
## 在stata中进行 probit and conditional logit 回归
## 简单介绍 ordered logistic regression


---
class: top, left

# 变量的类型（补充内容）

- 定量变量(quantitative)
 - 连续型（contineous）
 - 离散型(discrete) 
       1. 二值 (eg. Cropland ; Dose response)  
       2. 多值 (eg. Crop choice)

- 定性变量(qualitative)
 - 定序型(ordered)
 - 名义型(nominal)
      1. 二值 (eg. Vote)  
      2. 多值 (eg. Transportation)
 

连续型变量是定距变量,离散型、定序型、名义型都是分类型变量(categorical)。
   

---
class: top, left
- 定量变量和定向变量
 - 定量变量的数字取值有实质性意义。
 - 定性变量的数字取值没有实质性意义，只是类别间的互斥性。

- 连续型定量变量和离散型定量变量举例
 - 连续型定量变量：收入、社会经济地位指数
 - 离散型定量变量： 家庭子女数量、犯罪案件数、考上重点大学的人数
 
- 定序变量和名义变量的区别
 -  定序变量利用了变量取值次序先后的信息，但数字仅反映排列次序，相邻值间的距离不作要求。eg. 1="强烈赞成",2="赞成",3="中立",4="反对",5="强烈反对"。这里相邻数值之间的距离并不是相应态度在真实程度上的差异的体现。
 -  名义变量，数值既没有实质性含义，也不利用排序信息。eg. 1="未婚",2="已婚",3="离婚",4="丧偶"。
 

.footnote[
[参考资料] 丹尼尔·A·鲍威斯&谢宇.《分类数据分析的统计方法》.2008。
]


---
关于**probit regression** 的实例：
 [PROBIT REGRESSION | STATA DATA ANALYSIS EXAMPLES](https://stats.idre.ucla.edu/stata/dae/probit-regression/). 
 
关于**probit regression** 的实例：
 [ORDERED LOGISTIC REGRESSION | STATA DATA ANALYSIS EXAMPLES](https://stats.idre.ucla.edu/stata/dae/ordered-logistic-regression/)


---

class: center, middle

# Thanks!

---